Vezetéknév = input('Sári ')
Keresztnév = input('Balázs ')
év = input('2005')
csillagjegy = ('mérleg')
print('Önnek', Vezetéknév, 'a vezetékneve.')
print('Önnek', Keresztnév, 'a kersztneve')
print('A te neved',Vezetéknév, Keresztnév,.')
print('A te születési éve', év,.')
print('A te csillagjegyed a', csillagjegy,')