vezetéknév = input('Mi a vezetékneved?')
keresztnév = input('Mi a keresztneved?')
év = input('Mi a születési éved?')
csillagjegy = input('Mi a csillagjegyed?')
print('A te neved ', vezetéknév, keresztnév, '.', sep='')
print('A te születési éved ',év , 'és a csillagjegyed', csillagjegy, '.', sep='')